name: "FAP: Build and lint"
on: [push, pull_request]

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build for Dev branch"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          lfs: true

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app
        with:
          sdk-channel: dev

      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        with:
          skip-setup: true
          task: lint
